/**
 * Golden-fixture parity: the TS parser must produce structurally identical
 * output to the Python reference (tools/catalog/guildrun_parse_reference.py)
 * on 13 real log files — 41 runs, 439 battles, 8 beaten.
 *
 * fixtures/golden/runs.json.gz was generated by the Python parser and verified
 * against the game's own MessagePack Profile save (TotalStartedRuns=41,
 * TotalRunsBeaten=8), so parity here chains all the way to ground truth.
 */

import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseGuildrunLogs, type LogFile, type Run } from "../src/index.js";

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), "../../../fixtures");

function loadLogs(): LogFile[] {
  const dir = join(FIXTURES, "logs");
  return readdirSync(dir)
    .filter((f) => f.endsWith(".log.gz"))
    .sort()
    .map((f) => ({
      name: f.replace(/\.gz$/, ""),
      text: gunzipSync(readFileSync(join(dir, f))).toString("utf-8"),
    }));
}

function loadGolden(): Run[] {
  return JSON.parse(
    gunzipSync(readFileSync(join(FIXTURES, "golden", "runs.json.gz"))).toString("utf-8"),
  ) as Run[];
}

describe("golden parity with Python reference parser", () => {
  const logs = loadLogs();
  const golden = loadGolden();
  const { runs } = parseGuildrunLogs(logs);

  it("loads all 13 fixture logs", () => {
    expect(logs).toHaveLength(13);
  });

  it("finds 41 runs (matches the game's own Profile save)", () => {
    expect(runs).toHaveLength(41);
    expect(golden).toHaveLength(41);
  });

  it("finds 439 battles, 362W/77L", () => {
    const battles = runs.flatMap((r) => r.battles);
    expect(battles).toHaveLength(439);
    expect(battles.filter((b) => b.outcome === "victory")).toHaveLength(362);
    expect(battles.filter((b) => b.outcome === "defeat")).toHaveLength(77);
  });

  it("finds 8 beaten runs (matches the game's own Profile save)", () => {
    expect(runs.filter((r) => r.beaten)).toHaveLength(8);
  });

  it("matches per-run summary fields", () => {
    const summary = (rs: Run[]) =>
      rs.map((r) => ({
        start_ts: r.start_ts,
        seed: r.seed,
        difficulty: r.difficulty,
        floors_reached: r.floors_reached,
        battles_won: r.battles_won,
        battles_lost: r.battles_lost,
        beaten: r.beaten,
        endless_battles: r.endless_battles,
        event_fights: r.event_fights,
        lives_lost: r.lives_lost,
        n_battles: r.battles.length,
        n_shops: r.shops.length,
      }));
    expect(summary(runs)).toEqual(summary(golden));
  });

  it("matches the Python output structurally, in full", () => {
    // Round-trip through JSON so undefined-vs-missing cannot mask differences.
    const ours = JSON.parse(JSON.stringify(runs));
    expect(ours).toEqual(golden);
  });
});
